DROP TABLE data_50001;
CREATE TABLE data_50001 (
    id	                integer UNIQUE NOT NULL,
    parent	            integer,
    type	            varchar(50),
    name	            TEXT,
    v_total	            integer,
    dot_sub	            integer,
    sw_eu	            integer,
    swiad_fiz	        integer,
    wspolfin_eu	        integer,
    wyd_dlug	        integer,
    wyd_jednostek	    integer,
    wyd_majatk          integer,
    czesc	            varchar(10),
    info	            TEXT,
    leaf	            boolean,
    numer	            varchar(25),
    pozycja	            integer
);

DROP TABLE data_50002;
CREATE TABLE data_50002 ( 
    id	            integer,
    name	        text,
    parent	        integer,
    type	        text,
    v_nation        integer,
    czesc	        varchar(10),
    czesc_name	    varchar(50),
    info	        text,
    leaf	        boolean
);

DROP TABLE data_50003;
CREATE TABLE data_50003 ( 
    id	            integer,
    name	        text,
    parent	        integer,
    type	        text,
    v_nation        integer,
    czesc	        varchar(10),
    czesc_name	    varchar(50),
    info	        text,
    leaf	        boolean
);

DROP TABLE data_50004;
CREATE TABLE data_50004 ( 
    id	            integer,
    parent	        integer,
    type	        text,
    name	        text,
    v_nation        integer,
    leaf	        boolean
);

DROP TABLE data_50005;
CREATE TABLE data_50005 ( 
    id	            integer,
    parent	        integer,
    type	        text,
    name	        text,
    v_nation        integer,
    leaf	        boolean
);

DROP TABLE data_50006;
CREATE TABLE data_50006 ( 
    id	                                                            integer,
    parent	                                                        integer,
    type	                                                        text,
    name	                                                        text,
    grupa_paragrafow                                            	text,
    rodzaj_finansowania_wydatkow	                                text,
    plan_po_zmianach	                                            bigint,
    wydatki_ktore_nie_wygasly_z_uplywem_biezacego_roku_budzetowego	bigint,
    wykonanie_wydatkow	                                            bigint,
    zaangazowanie	                                                bigint,
    zobowiazania_ogolem	                                            bigint,
    zobowiazania_wymagalne_powstale_w_latach_ubieglych	            bigint,
    zobowiazania_wymagalne_powstale_w_roku_biezacym                 bigint,
    leaf	                                                        boolean
);

DROP TABLE data_50007;
CREATE TABLE data_50007 ( 
    id	            integer,
    parent	        integer,
    type	        text,
    name	        text,
    v_eu            integer,
    czesc           varchar(10),
    leaf	        boolean
);

DROP TABLE data_50008;
CREATE TABLE data_50008 ( 
    id	            integer,
    name	        text,
    parent	        integer,
    type	        text,
    v_eu            integer,
    czesc	        varchar(10),
    czesc_name	    varchar(50),
    info	        text,
    leaf	        boolean
);

DROP TABLE data_50009;
CREATE TABLE data_50009 ( 
    id	            integer,
    name	        text,
    parent	        integer,
    type	        text,
    v_eu            integer,
    czesc	        varchar(10),
    czesc_name	    varchar(50),
    info	        text,
    leaf	        boolean
);

DROP TABLE data_50010;
CREATE TABLE data_50010 ( 
    id	            integer,
    parent	        integer,
    type	        text,
    name	        text,
    v_eu            integer,
    leaf	        boolean
);

DROP TABLE data_50011;
CREATE TABLE data_50011 ( 
    id	            integer,
    parent	        integer,
    type	        text,
    name	        text,
    v_eu            integer,
    leaf	        boolean
);

--CREATE TABLE data_50012 ( id	,
--info	,
--leaf	,
--name	,
--parent	,
--type	,
--val_2011	,
--val_2012	,
--val_2013 );
--CREATE TABLE data_50013 ( frst_popr	,
--id	,
--info	,
--leaf	,
--name	,
--paragrafy	,
--parent	,
--plan_nast	,
--type );
--CREATE TABLE data_50014 ( id	,
--info	,
--leaf	,
--name	,
--parent	,
--type	,
--val_2011	,
--val_2012	,
--val_2013 );
--CREATE TABLE data_50015 ( frst_popr	,
--id	,
--info	,
--leaf	,
--name	,
--parent	,
--plan_nast	,
--type );
--CREATE TABLE data_50016 ( centrala	,
--dolnoslaskie	,
--id	,
--info	,
--kujawskopomorskie	,
--leaf	,
--lodzki	,
--lubelski	,
--lubuski	,
--malopolski	,
--mazowiecki	,
--name	,
--ogolem	,
--opolski	,
--osrodki_wojewodzkie	,
--parent	,
--podkarpacki	,
--podlaski	,
--pomorski	,
--slaski	,
--swietokrzyski	,
--type	,
--warminskomazurski	,
--wielkopolski	,
--zachodniopomorski );
--CREATE TABLE data_50017 ( id	,
--leaf	,
--name	,
--parent	,
--type	,
--val );
--CREATE TABLE data_50018 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50019 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50020 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50021 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50022 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50023 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50024 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50025 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50026 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50027 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50028 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50029 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50030 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50031 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50032 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50033 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50034 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
--CREATE TABLE data_50035 ( data-podpisania-umowyaneksu	,
--data-utworzenia-w-ksi-simik-07-13-umowyaneksu	,
--dofinansowanie	,
--dofinansowanie-ue	,
--dzialanie-kod	,
--forma-prawna	,
--id	,
--kod-pocztowy	,
--leaf	,
--miejscowosc	,
--name	,
--nazwa-beneficjenta	,
--nip-beneficjenta	,
--numer-umowydecyzji	,
--obszar-realizacji	,
--os-priorytetowa-kod	,
--ostatni-wniosek-o-platnosc-dla-najbardziej-aktualnej-umowyaneksu	,
--parent	,
--poddzialanie-kod	,
--powiat	,
--program-operacyjny-nazwa	,
--projekt-zakonczony-wniosek-o-platnosc-koncowa	,
--temat-priorytetu	,
--type	,
--wartosc-ogolem	,
--wojewodztwo	,
--wydatki-kwalifikowalne );
